version: "3"
services:
  nginx:
    image: ravioo/nginx:latest
    links:
      - web:web
    ports:
      - "49160:8080"
  web:
    image: ravioo/web_chat:latest
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
